// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: dummy.sql

package models

import (
	"context"
)

const dummyQuery = `-- name: DummyQuery :one

SELECT 1
`

// This is for sqlc to generate a dummy query when it makes the DTO (models) code.
// see sqlc.yaml
func (q *Queries) DummyQuery(ctx context.Context) (int32, error) {
	row := q.db.QueryRowContext(ctx, dummyQuery)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
