/*
    Getting a couple of test users in the database
*/
INSERT INTO `cushondb`.`user` (`name_title`, `name_first`, `name_last`, `email`)
    VALUES ('Mr', 'John', 'Doeman', 'j.doeson@mymail.net');

INSERT INTO `cushondb`.`user` (`name_title`, `name_first`, `name_last`, `email`)
    VALUES ('Ms', 'Daria', 'Fooson', 'fooson_d@hotmail.xyz');
/**
  Seed the fund table with the initial fund. We only have 1 fund at this time
  The UUID is generated by the database engine and the title must be unique
 */

INSERT INTO `cushondb`.`fund` (`title`, `description`)
    VALUES (
        'Cushon Equities Fund',
        'A balanced and well diversified fund focused on sustainable long term growth'
    );
/**
  Add a couple of products
   - A bog-standard workplace pension product
   - A retail ISA, available to individuals. Supports selection from a list of funds.

  UUID is generated by the database engine.
  The title must be unique across the product type

 */

INSERT INTO `cushondb`.`product` (`title`, `type`, `description`)
    VALUES ('Cushon Work Pension', 'employer', 'Standard workplace pension product');

INSERT INTO `cushondb`.`product` (`title`, `type`, `description`)
    VALUES ('Cushon Flexible ISA', 'direct', 'A retail ISA, available to individuals. Select your own fund(s) within. At the moment only 1 fund is available');
/**
  Adding a dummy employer, to show the relationship
  between employers and employer-pension products

  Although it's not required for this project,
  we could have a user-employer table showing current and past employers for each user.
  (The user may have been with multiple employers who have Cushon pension products.)

  In any case, the relationship can be inferred through the user_account table
 */

INSERT INTO `cushondb`.`employer` (`title`)
    VALUES ('FreshCo Supermarkets Limited');

/**
  User 1 has a standard employer pension with a balance
  That user's pension is invested in a single fund, as per the product's default
  But this design allows for different users, when policies change, to have different fund combinations
  even in their workplace pension
*/
INSERT INTO `cushondb`.`user_account` (`user_id`, `product_id`, `total_investment`, `current_balance`)
    VALUES ('1', '1', '6000', '6795.42');
INSERT INTO `cushondb`.`user_account_funds` (`fund_id`, `user_account_id`, `weight_pc`)
    VALUES ('1', '1', '100');
INSERT INTO `cushondb`.`user_account_transaction` (`account_id`, `created`, `amount`)
VALUES
    ('1', '2023-03-01', '250'),
    ('1', '2023-04-01', '250'),
    ('1', '2023-05-01', '250'),
    ('1', '2023-06-01', '250'),
    ('1', '2023-07-01', '250'),
    ('1', '2023-08-01', '250'),
    ('1', '2023-09-01', '250'),
    ('1', '2023-10-01', '250'),
    ('1', '2023-11-01', '250'),
    ('1', '2023-12-01', '250'),
    ('1', '2024-01-01', '250'),
    ('1', '2024-02-01', '250'),
    ('1', '2024-03-01', '250'),
    ('1', '2024-04-01', '250'),
    ('1', '2024-05-01', '250'),
    ('1', '2024-06-01', '250'),
    ('1', '2024-07-01', '250'),
    ('1', '2024-08-01', '250'),
    ('1', '2024-09-01', '250'),
    ('1', '2024-10-01', '250'),
    ('1', '2024-11-01', '250'),
    ('1', '2024-12-01', '250'),
    ('1', '2025-01-01', '250'),
    ('1', '2025-02-01', '250');


/** User 2 has no product relationship (yet), except a platform login account */

