#version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: cushon-local-db
    environment:
      MYSQL_ROOT_PASSWORD: localdev
      MYSQL_DATABASE: cushondb
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5
