/**
  Seed the fund table with the initial fund. We only have 1 fund at this time
  The UUID is generated by the database engine and the title must be unique
 */

INSERT INTO `cushondb`.`fund` (`title`, `description`)
    VALUES (
        'Cushon Equities Fund',
        'A balanced and well diversified fund focused on sustainable long term growth'
    );
