/**
  Add a couple of products
   - A bog-standard workplace pension product
   - A retail ISA, available to individuals. Supports selection from a list of funds.

  UUID is generated by the database engine.
  The title must be unique across the product type

 */

INSERT INTO `cushondb`.`product` (`title`, `type`, `description`)
    VALUES ('Cushon Work Pension', 'employer', 'Standard workplace pension product');

INSERT INTO `cushondb`.`product` (`title`, `type`, `description`)
    VALUES ('Cushon Flexible ISA', 'direct', 'A retail ISA, available to individuals. Select your own fund(s) within. At the moment only 1 fund is available');
